select * from customer limit 20

--Total revenue generated by male Vs Female customer
select gender, SUM(purchase_amount) as revenue 
from customer
group by gender

--customer used discount still spent more money than average purchase amount
select customer_id, purchase_amount
from customer
where discount_applied= 'Yes' and purchase_amount>= (select AVG(purchase_amount) from customer)

--5 top products with the highest average review rating?
select item_purchased, ROUND(AVG(review_rating :: numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg (review_rating) desc
limit 5


---Compare the average purchase amount between standard and express shipping

select shipping_type, ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type


--Do suscribers spend more? Compare average spend  and total revenue between subscribers and non-suscribers.
select subscription_status,
count(customer_id) as total_customers,
Round(AVG(purchase_amount),2) as avg_spend,
Round(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc

--5 products have the highest percentage of purchases with discount applied?
select item_purchased,
ROUND(100*SUM(CASE WHEN discount_applied='Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate	
from customer
group by item_purchased
order by discount_rate desc
limit 5

--segment customer into NEW, Returning and Loyal Based on their total number of previous purchases,
--and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
CASE 
	WHEN previous_purchases=1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 and 10 thEN 'Returning'
	ELSE 'Loyal'
	END as customer_segment
from customer
)

select customer_segment, count (*) as "Number of Customers"
from customer_type
group by customer_segment

--top 3 most purchased products in each category? 
with item_counts as(
select category, item_purchased,
COUNT(customer_id) as total_orders,
ROW_NUMBER() over (partition by category order by count (customer_id) DESC) as item_rank
from customer
group by category , item_purchased
)
select item_rank,category, item_purchased, total_orders
from item_counts
where item_rank<=3

--customers who are repeat buyers (more than 5 previous purchases ) also likely to subscribe?
select subscription_status,
COUNT (customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--revenue contribution of each age group?
select age_group,
SUM(purchase_amount) as total_revenue
from customer 
group by age_group
order by total_revenue desc